"""baseline schema (legacy 001-018)

Revision ID: f657b43da148
Revises: 
Create Date: 2026-08-25 19:20:31.361328

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f657b43da148'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.String(length=50), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sponsor_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sponsor_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_profiles_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_sponsor_profiles_sort_order'), ['sort_order'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('credits_balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('last_login', sa.Float(), nullable=True),
    sa.Column('register_ip', sa.String(length=45), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('registration_channel', sa.String(length=20), nullable=True),
    sa.Column('invite_code_id', sa.Integer(), nullable=True),
    sa.Column('github_id', sa.String(length=50), nullable=True),
    sa.Column('linuxdo_id', sa.String(length=50), nullable=True),
    sa.Column('oauth_provider', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_github_id'), ['github_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_invite_code_id'), ['invite_code_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_linuxdo_id'), ['linuxdo_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_registration_channel'), ['registration_channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('code_type', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_codes_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_codes_id'), ['id'], unique=False)

    op.create_table('credit_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_transactions_transaction_type'), ['transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('daily_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('checkin_date', sa.String(length=10), nullable=False),
    sa.Column('reward_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'checkin_date', name='uq_daily_checkins_user_date')
    )
    with op.batch_alter_table('daily_checkins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_checkins_checkin_date'), ['checkin_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_checkins_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_checkins_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_checkins_user_id'), ['user_id'], unique=False)

    op.create_table('global_master_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('html_template', sa.Text(), nullable=True),
    sa.Column('svg_template', sa.Text(), nullable=True),
    sa.Column('preview_image', sa.Text(), nullable=True),
    sa.Column('import_summary', sa.JSON(), nullable=True),
    sa.Column('style_config', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('global_master_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_global_master_templates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_global_master_templates_user_id'), ['user_id'], unique=False)

    op.create_table('invite_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('credits_amount', sa.Integer(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invite_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_codes_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_invite_codes_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_invite_codes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_invite_codes_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_invite_codes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invite_codes_is_active'), ['is_active'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('scenario', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('outline', sa.JSON(), nullable=True),
    sa.Column('slides_html', sa.Text(), nullable=True),
    sa.Column('slides_data', sa.JSON(), nullable=True),
    sa.Column('confirmed_requirements', sa.JSON(), nullable=True),
    sa.Column('project_metadata', sa.JSON(), nullable=True),
    sa.Column('design_spec', sa.JSON(), nullable=True),
    sa.Column('design_spec_version', sa.Integer(), nullable=False),
    sa.Column('design_spec_locked', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('share_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_project_id'), ['project_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_projects_share_token'), ['share_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_projects_user_id'), ['user_id'], unique=False)

    op.create_table('redemption_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('credits_amount', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('redemption_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_redemption_codes_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_redemption_codes_id'), ['id'], unique=False)

    op.create_table('user_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=24), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('salt', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('last_used_at', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_api_keys_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_api_keys_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_api_keys_key_hash'), ['key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_api_keys_key_prefix'), ['key_prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_api_keys_user_id'), ['user_id'], unique=False)

    op.create_table('user_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=True),
    sa.Column('config_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'config_key', name='uq_user_config_key')
    )
    with op.batch_alter_table('user_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_configs_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_configs_config_key'), ['config_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_configs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_configs_user_id'), ['user_id'], unique=False)

    op.create_table('user_metrics',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_active_at', sa.Float(), nullable=True),
    sa.Column('projects_count', sa.Integer(), nullable=False),
    sa.Column('credits_consumed_total', sa.Integer(), nullable=False),
    sa.Column('credits_recharged_total', sa.Integer(), nullable=False),
    sa.Column('last_project_created_at', sa.Float(), nullable=True),
    sa.Column('last_credit_consumed_at', sa.Float(), nullable=True),
    sa.Column('last_credit_recharged_at', sa.Float(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('user_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_metrics_last_active_at'), ['last_active_at'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_session_id'), ['session_id'], unique=True)

    op.create_table('export_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('job_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('export_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_jobs_task_id'), ['task_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_export_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('invite_code_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invite_code_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('credits_granted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['invite_code_id'], ['invite_codes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invite_code_usages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_code_usages_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_invite_code_usages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_invite_code_usages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invite_code_usages_invite_code_id'), ['invite_code_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invite_code_usages_user_id'), ['user_id'], unique=True)

    op.create_table('narration_audios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('slide_index', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('voice', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.String(length=20), nullable=False),
    sa.Column('audio_format', sa.String(length=10), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('cues_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'slide_index', 'language', 'provider', 'voice', 'rate', 'content_hash', name='uq_narration_audio_cache')
    )
    with op.batch_alter_table('narration_audios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_narration_audios_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_narration_audios_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_narration_audios_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_narration_audios_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_narration_audios_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_narration_audios_slide_index'), ['slide_index'], unique=False)

    op.create_table('ppt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('html_template', sa.Text(), nullable=False),
    sa.Column('applicable_scenarios', sa.JSON(), nullable=True),
    sa.Column('style_config', sa.JSON(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ppt_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ppt_templates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ppt_templates_template_type'), ['template_type'], unique=False)

    op.create_table('project_reference_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('parse_status', sa.String(length=32), nullable=False),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('include_in_prompt', sa.Boolean(), nullable=False),
    sa.Column('parse_mode_used', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_reference_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_reference_files_file_id'), ['file_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_project_reference_files_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_reference_files_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_reference_files_user_id'), ['user_id'], unique=False)

    op.create_table('project_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_versions_id'), ['id'], unique=False)

    op.create_table('reference_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'chunk_index', name='uq_reference_chunks_file_chunk')
    )
    with op.batch_alter_table('reference_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reference_chunks_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reference_chunks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reference_chunks_project_id'), ['project_id'], unique=False)

    op.create_table('speech_scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('slide_index', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('slide_title', sa.String(length=255), nullable=False),
    sa.Column('script_content', sa.Text(), nullable=False),
    sa.Column('estimated_duration', sa.String(length=50), nullable=True),
    sa.Column('speaker_notes', sa.Text(), nullable=True),
    sa.Column('generation_type', sa.String(length=20), nullable=False),
    sa.Column('tone', sa.String(length=50), nullable=False),
    sa.Column('target_audience', sa.String(length=100), nullable=False),
    sa.Column('custom_audience', sa.Text(), nullable=True),
    sa.Column('language_complexity', sa.String(length=20), nullable=False),
    sa.Column('speaking_pace', sa.String(length=20), nullable=False),
    sa.Column('custom_style_prompt', sa.Text(), nullable=True),
    sa.Column('include_transitions', sa.Boolean(), nullable=False),
    sa.Column('include_timing_notes', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('speech_scripts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_speech_scripts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_speech_scripts_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_speech_scripts_project_id'), ['project_id'], unique=False)

    op.create_table('todo_boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('current_stage_index', sa.Integer(), nullable=False),
    sa.Column('overall_progress', sa.Float(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    with op.batch_alter_table('todo_boards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_todo_boards_id'), ['id'], unique=False)

    op.create_table('slide_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('slide_index', sa.Integer(), nullable=False),
    sa.Column('slide_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('slide_metadata', sa.JSON(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('is_user_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['ppt_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slide_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slide_data_id'), ['id'], unique=False)

    op.create_table('todo_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('todo_board_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('stage_id', sa.String(length=100), nullable=False),
    sa.Column('stage_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['todo_board_id'], ['todo_boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('todo_stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_todo_stages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_todo_stages_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_todo_stages_stage_id'), ['stage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_todo_stages_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todo_stages_status'))
        batch_op.drop_index(batch_op.f('ix_todo_stages_stage_id'))
        batch_op.drop_index(batch_op.f('ix_todo_stages_project_id'))
        batch_op.drop_index(batch_op.f('ix_todo_stages_id'))

    op.drop_table('todo_stages')
    with op.batch_alter_table('slide_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slide_data_id'))

    op.drop_table('slide_data')
    with op.batch_alter_table('todo_boards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todo_boards_id'))

    op.drop_table('todo_boards')
    with op.batch_alter_table('speech_scripts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_speech_scripts_project_id'))
        batch_op.drop_index(batch_op.f('ix_speech_scripts_language'))
        batch_op.drop_index(batch_op.f('ix_speech_scripts_id'))

    op.drop_table('speech_scripts')
    with op.batch_alter_table('reference_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reference_chunks_project_id'))
        batch_op.drop_index(batch_op.f('ix_reference_chunks_id'))
        batch_op.drop_index(batch_op.f('ix_reference_chunks_file_id'))

    op.drop_table('reference_chunks')
    with op.batch_alter_table('project_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_versions_id'))

    op.drop_table('project_versions')
    with op.batch_alter_table('project_reference_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_reference_files_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_reference_files_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_reference_files_id'))
        batch_op.drop_index(batch_op.f('ix_project_reference_files_file_id'))

    op.drop_table('project_reference_files')
    with op.batch_alter_table('ppt_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ppt_templates_template_type'))
        batch_op.drop_index(batch_op.f('ix_ppt_templates_id'))

    op.drop_table('ppt_templates')
    with op.batch_alter_table('narration_audios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_narration_audios_slide_index'))
        batch_op.drop_index(batch_op.f('ix_narration_audios_provider'))
        batch_op.drop_index(batch_op.f('ix_narration_audios_project_id'))
        batch_op.drop_index(batch_op.f('ix_narration_audios_language'))
        batch_op.drop_index(batch_op.f('ix_narration_audios_id'))
        batch_op.drop_index(batch_op.f('ix_narration_audios_content_hash'))

    op.drop_table('narration_audios')
    with op.batch_alter_table('invite_code_usages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_code_usages_user_id'))
        batch_op.drop_index(batch_op.f('ix_invite_code_usages_invite_code_id'))
        batch_op.drop_index(batch_op.f('ix_invite_code_usages_id'))
        batch_op.drop_index(batch_op.f('ix_invite_code_usages_created_at'))
        batch_op.drop_index(batch_op.f('ix_invite_code_usages_channel'))

    op.drop_table('invite_code_usages')
    with op.batch_alter_table('export_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_export_jobs_task_id'))
        batch_op.drop_index(batch_op.f('ix_export_jobs_project_id'))
        batch_op.drop_index(batch_op.f('ix_export_jobs_id'))

    op.drop_table('export_jobs')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_session_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_id'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('user_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_metrics_last_active_at'))

    op.drop_table('user_metrics')
    with op.batch_alter_table('user_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_configs_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_configs_id'))
        batch_op.drop_index(batch_op.f('ix_user_configs_config_key'))
        batch_op.drop_index(batch_op.f('ix_user_configs_category'))

    op.drop_table('user_configs')
    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_api_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_api_keys_key_prefix'))
        batch_op.drop_index(batch_op.f('ix_user_api_keys_key_hash'))
        batch_op.drop_index(batch_op.f('ix_user_api_keys_is_active'))
        batch_op.drop_index(batch_op.f('ix_user_api_keys_id'))

    op.drop_table('user_api_keys')
    with op.batch_alter_table('redemption_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_redemption_codes_id'))
        batch_op.drop_index(batch_op.f('ix_redemption_codes_code'))

    op.drop_table('redemption_codes')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_user_id'))
        batch_op.drop_index(batch_op.f('ix_projects_share_token'))
        batch_op.drop_index(batch_op.f('ix_projects_project_id'))
        batch_op.drop_index(batch_op.f('ix_projects_id'))

    op.drop_table('projects')
    with op.batch_alter_table('invite_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_codes_is_active'))
        batch_op.drop_index(batch_op.f('ix_invite_codes_id'))
        batch_op.drop_index(batch_op.f('ix_invite_codes_expires_at'))
        batch_op.drop_index(batch_op.f('ix_invite_codes_created_at'))
        batch_op.drop_index(batch_op.f('ix_invite_codes_code'))
        batch_op.drop_index(batch_op.f('ix_invite_codes_channel'))

    op.drop_table('invite_codes')
    with op.batch_alter_table('global_master_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_master_templates_user_id'))
        batch_op.drop_index(batch_op.f('ix_global_master_templates_id'))

    op.drop_table('global_master_templates')
    with op.batch_alter_table('daily_checkins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_checkins_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_checkins_id'))
        batch_op.drop_index(batch_op.f('ix_daily_checkins_created_at'))
        batch_op.drop_index(batch_op.f('ix_daily_checkins_checkin_date'))

    op.drop_table('daily_checkins')
    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_credit_transactions_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_credit_transactions_id'))
        batch_op.drop_index(batch_op.f('ix_credit_transactions_created_at'))

    op.drop_table('credit_transactions')
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_codes_id'))
        batch_op.drop_index(batch_op.f('ix_verification_codes_email'))

    op.drop_table('verification_codes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_registration_channel'))
        batch_op.drop_index(batch_op.f('ix_users_linuxdo_id'))
        batch_op.drop_index(batch_op.f('ix_users_invite_code_id'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_github_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('sponsor_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sponsor_profiles_sort_order'))
        batch_op.drop_index(batch_op.f('ix_sponsor_profiles_is_active'))
        batch_op.drop_index(batch_op.f('ix_sponsor_profiles_id'))

    op.drop_table('sponsor_profiles')
    # ### end Alembic commands ###
